export const languages = [
    { code: 'eng', name: 'English' },
    { code: 'cmh', name: '简体中文' },
    { code: 'hin', name: 'हिन्दी' },
    { code: 'spa', name: 'Español' },
    { code: 'ara', name: 'العربية' },
    { code: 'fra', name: 'Français' },
    { code: 'ben', name: 'বাংলা' },
    { code: 'por', name: 'Português' },
    { code: 'rus', name: 'Русский' },
    { code: 'urd', name: 'اردو' },
    { code: 'ind', name: 'Indonesia' },
    { code: 'deu', name: 'Deutsch' },
    { code: 'jpn', name: '日本語' },
    { code: 'mar', name: 'मराठी' },
    { code: 'tel', name: 'తెలుగు' },
    { code: 'ita', name: 'Italiano' },
    { code: 'jav', name: 'Basa Jawa' },
    { code: 'kor', name: '한국어' },
    { code: 'tur', name: 'Türkçe' },
    { code: 'hau', name: 'Hausa' },
    { code: 'tam', name: 'தமிழ்' },
    { code: 'swa', name: 'Kiswahili' },
    { code: 'vie', name: 'Tiếng Việt' },
    { code: 'pes', name: 'فارسی' },
    { code: 'tha', name: 'ไทย' },
    { code: 'amh', name: 'አማርኛ' },
    { code: 'mya', name: 'မြန်မာ' },
    { code: 'pus', name: 'پښتو' },
    { code: 'pol', name: 'Polski' },
    { code: 'nld', name: 'Nederlands' },
    { code: 'ell', name: 'Ελληνικά' },
    { code: 'ces', name: 'Czech' },
    { code: 'heb', name: 'עברית' },
    { code: 'yor', name: 'Yoruba' },
    { code: 'zul', name: 'Zulu' },
    { code: 'swe', name: 'Svenska' },
    { code: 'bul', name: 'Български' },
    { code: 'pan', name: 'ਪੰਜਾਬੀ' }
];